### PR TITLE
Use Persistent Filter

### PR DESCRIPTION
**Pull request by chadhietala**
The persistent filter allows for both in between rebuild catching and
also warm boot as we persist the last state to the system tmp directory.

https://github.com/stefanpenner/broccoli-persistent-filter

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please see: https://github.com/sindresorhus/broccoli-defeatureify/pull/2#issuecomment-133422506

I'd rather wait until it's in `broccoli-filter`.

// @stefanpenner

**Comment by stefanpenner** [comment]
@sindresorhus ya it was my impression that we would be able to merge persistence caches into broccoli-filter quickly, but it looks like that may not be any time soon.... In light of that, we have spent some-time getting broccoli-persistent-filter into good working order, and upgrading all our performance sensitive deps to it.

I would recommend this be merged, once (in the future) broccoli-filter supports this, we can circle around and submit another PR here.

**Comment by sindresorhus** [comment]
Alright.

@chadhietala Please look through the feedback and changes on: https://github.com/sindresorhus/broccoli-defeatureify/pull/2 I don't want to have to repeat myself.

**Comment by sindresorhus** [comment]
ping @chadhietala

**Comment by sindresorhus** [comment]
Closing for lack of response. Happy to reopen if this is ever finished.

**Pull request closed without merging**
